### ISSUE TITLE
"stepSize" attribute is ignored in slider input dialogs using script editor

### ISSUE THREAD

**Issue by LeonYang5114** [scijava/scijava-common#205]
In https://github.com/imagej/imagej-ui-swing/issues/64

@imagejan mentioned that stepSize attribute is ignored, for example, when calling:
```
// @int(label="test", min="0", max="100", stepSize="10", style="slider") a
print(a)
```
Notice that there is another bug here, which is that min/max must be specified or it will hang the program.

After some investigation, it seems that this is due to some [known bug](https://github.com/scijava/scijava-common/blob/f1d2b4d1b733689e34ab578ec0656c88675d3ffc/src/main/java/org/scijava/script/ScriptInfo.java#L474-L477) as there is a "FIX ME" in the code. 

I think the reason to this bug is that there is no converter that converts String to Number in Scijava right now. We could create such converter. But I don't understand why we want to [use Number as the type for stepSize](https://github.com/scijava/scijava-common/blob/35163f8e93e526ab75f710f014f4600ded4398b4/src/main/java/org/scijava/module/MutableModuleItem.java#L73). If the input is an `int`, then max/min/stepSize should all be `int`, right? Same should apply to `double` `long` etc. Then we can just use `item.getType` as the type to parse the stepSize String given. @ctrueden

**Comment by ctrueden** [comment]
When I first designed the `ModuleItem` interface, `stepSize` was indeed typed on `T`. And there was problem with it, which I worked around by typing it on `Number`. It is probably not correct, but it's how things are for now. We could consider changing it for SciJava Common 3.0.0 I suppose.

Anyway, this issue is fixed in c0ffe3956e8ccc08cc633ade9b00bb31a43f0de2.
