### ISSUE TITLE
Erroneous recording of @File parameters

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-common#235]
The following IJ1 macro,

```
// @File(label="Choose a folder", style="directory") folder

print(folder)
```

when placed as `Select_Folder.ijm` somewhere inside `./plugins/Scripts` of a Fiji installation, will be recorded as:

```
run("Select Folder", "choose=C:\\tmp\\test\\ folder=C:\tmp\test");
```

whereas it _should_ be:

```
run("Select Folder", "folder=C:\\tmp\\test");
```

i.e. record the variable _name_ (`folder`) only, and escape backslashes in the parameter.

**Comment by ctrueden** [comment]
Interesting bug. This took me some time to figure out. It is not a bug in SciJava Common, but (shockingly :wink:) the ImageJ Legacy component.

What's happening is: the ImageJ1 macro recorder takes the liberty of adding "choose=foo" to the static `commandOptions` tally (via `Recorder.recordPath`) whenever an ImageJ1 file chooser dialog is shown.

Patch coming shortly.

**Comment by ctrueden** [comment]
@imagejan If you care to test that `imagej-legacy` patch, I will merge if it works for you.

It would be helpful if you could try a somewhat less trivial script too just to make sure this fix does not introduce any unintended side effects. (I _think_ it is OK to disable the macro recording solely for the duration of file chooser invoked via the SciJava `UIService`, but I am not 100% sure that something somewhere else won't get hosed up because of it.)

**Comment by imagejan** [comment]
@ctrueden thanks for the quick fix!
It indeed records only the expected `folder` parameter now.

    run("Select Folder", "folder=C:\tmp\test");

However, it still records _single backslashes_ on Windows, i.e. the resulting macro line fails to be parsed correctly because it contains escaped characters.

    run("Select Folder", "folder=C:\\tmp\\test");

**Comment by ctrueden** [comment]
Ah, thanks, I missed that. So this was really two bugs in one. Actually, there was no escaping whatsoever, which could potentially hose everything in lots of fun ways.

I updated the `superfluous-file-params` branch. It works in my tests, but could you also please test again?
