### ISSUE TITLE
LogService should have non-consuming Handler plugins

### ISSUE THREAD

**Issue by hinerm** [scijava/scijava-common#84]
Depends on https://github.com/scijava/scijava-common/issues/83

We already have cases of competing `LogServices`, e.g. the `DefaultLogService` and `SLF4J`. It is becoming clear that there is a need for additional logging functionality, for example in the legacy layer we would like to pass error messages and exceptions to `IJ.log` or `IJ.handleException` functionality.

However this is not possible at the moment without competing with other `LogService` implementations.

Once we can differentiate consuming and non-consuming `Handler`s, though, we can refactor the `DefaultLogService` to use non-consuming `Handler` plugins. Then whichever implementations are present can log a given event as appropriate.

**Comment by ctrueden** [comment]
For the case of logging stdout/stderr specifically, the issue is now solved with #152. I am not seeing another immediate use case for non-consuming handlers. We sort of have a pattern like that already with the `ConsoleArgument` and `ConsoleService`; let's not complicate things any further for now, until/unless a clear need arises.
